// English study content for every Source Flashcard, keyed by stable FC id.
//
// Mandarin is the primary authority for English wording; Spanish is compared
// to preserve teaching intent. These fields are joined into the generated
// chino_flashcards.csv by scripts/build_flashcards.mjs. The application only
// ships English once every card is complete.
//
// Each entry is [ingles, explicacion_ingles, ejemplo_ingles, etiquetas_ingles]:
//   - ingles            meaning (palabra/frase) or English question (concepto)
//   - explicacion_ingles explanation (palabra/frase) or English answer (concepto)
//   - ejemplo_ingles    translation of the Spanish example sentence
//   - etiquetas_ingles  English hidden tags used for active-locale search

export const englishById = new Map([
  ["FC001", ["I", "First-person singular personal pronoun.", "I am a student.", "pronoun;basics"]],
  ["FC002", ["you", "Informal second-person singular pronoun.", "What is your name?", "pronoun;basics"]],
  ["FC003", ["you (polite)", "Respectful form of \u201Cyou\u201D, used with elders or in formal situations.", "How have you been lately?", "pronoun;formal;politeness"]],
  ["FC004", ["he", "Masculine third-person singular pronoun.", "His surname is Wu.", "pronoun"]],
  ["FC005", ["she", "Feminine third-person singular pronoun; pronounced the same as \u4ED6.", "She is F\u00E1tima.", "pronoun"]],
  ["FC006", ["it", "Third-person pronoun for animals or things; pronounced the same as he and she.", "It is fine.", "pronoun;animals;objects"]],
  ["FC007", ["plural suffix", "Added mainly to pronouns and nouns for people; it is not a general plural for objects.", "you (plural)", "grammar;plural"]],
  ["FC008", ["we", "Plural of I.", "We are students.", "pronoun;plural"]],
  ["FC009", ["you (plural)", "Plural of you.", "How have you all been lately?", "pronoun;plural"]],
  ["FC010", ["What is the difference between \u4ED6, \u5979, and \u5B83?", "All three are pronounced t\u0101. In writing, \u4ED6 is \u201Che\u201D, \u5979 is \u201Cshe\u201D, and \u5B83 is used for animals or things.", "All three characters are read as t\u0101.", "pronunciation;pronoun"]],
  ["FC011", ["In what order are the strokes of the character \u5341 written?", "First the horizontal stroke, then the vertical one.", "In \u5341, the horizontal stroke comes before the vertical one.", "writing;strokes"]],
  ["FC012", ["student", "A person who studies.", "I am a student.", "person;studies"]],
  ["FC013", ["recently / lately", "Refers to a period close to the present moment.", "How have you been lately?", "time;greeting"]],
  ["FC014", ["all right / not bad", "Informal response to say that something is acceptably good.", "I'm doing all right.", "state;response"]],
  ["FC015", ["this", "Points to something nearby.", "Whose name is this?", "demonstrative;basics"]],
  ["FC016", ["milk", "Literally it means \u201Ccow\u2019s milk\u201D.", "I drink milk.", "drink;basics"]],
  ["FC017", ["to drink", "Verb used for drinking liquids.", "drink milk", "verb;drink"]],
  ["FC018", ["son", "The usual way to say \u201Cson\u201D.", "He is my son.", "family;person"]],
  ["FC019", ["What is a radical and what is it for?", "It is the component used to classify and look up a character in the dictionary.", "In \u60A8, the classification radical is \u5FC3.", "radical;dictionary"]],
  ["FC020", ["heart (character and its radical forms)", "\u5FC3 means \u201Cheart\u201D and can act as a radical; when it appears on the side it often takes the form \u5FC4.", "\u60A8", "radical;character"]],
  ["FC021", ["person (character and its radical forms)", "\u4EBA means \u201Cperson\u201D; as a side component it is usually written \u4EBB.", "you; he", "radical;character"]],
  ["FC022", ["woman / feminine (character and component)", "Character and component linked to women or the feminine.", "she; good", "radical;family"]],
  ["FC023", ["father (formal character and component)", "It means \u201Cfather\u201D but usually appears in words like \u7236\u4EB2 or \u7236\u6BCD. For \u201Cdad\u201D, \u7238\u7238 is used.", "father / dad", "radical;family"]],
  ["FC024", ["mouth", "Character and radical related to the mouth or speech.", "question particle", "radical;character"]],
  ["FC025", ["to have / there is", "Basic verb expressing that someone has something or that something exists.", "I have class in the morning.", "verb;possession;existence;basics"]],
  ["FC026", ["child (as character or component)", "Carries the idea of \u201Cson\u201D or \u201Cchild\u201D. In everyday speech, \u513F\u5B50 and \u5B69\u5B50 are more common.", "well", "character;family"]],
  ["FC027", ["Chinese character", "The general name for the characters used to write Chinese.", "I study Chinese characters.", "writing;character;basics"]],
  ["FC028", ["good / fine", "Basic adjective with a positive meaning.", "very good", "basics;greeting"]],
  ["FC029", ["Hello!", "Basic greeting addressed to one person.", "Hello!", "greeting;basics"]],
  ["FC030", ["question particle for yes/no questions", "It is placed at the end of an affirmative sentence to turn it into a closed question.", "Are you a student?", "particle;question"]],
  ["FC031", ["How are you?", "Asks about someone\u2019s well-being. As a greeting it can sound textbook; \u4F60\u6700\u8FD1\u600E\u4E48\u6837 is more natural.", "How are you? I\u2019m very well.", "greeting;question"]],
  ["FC032", ["how / how about", "Asks about someone\u2019s state or their opinion about someone or something.", "How are you?", "question;greeting"]],
  ["FC033", ["How are you all?", "Asks about the state of several people.", "How are you all?", "greeting;plural"]],
  ["FC034", ["very", "Goes between the subject and an adjective; it is often not translated literally as \u201Cvery\u201D.", "I am very well.", "adverb;degree"]],
  ["FC035", ["very good", "Positive reply when asked how someone is.", "I am very well.", "state;greeting"]],
  ["FC036", ["not", "Negation placed before a verb or adjective.", "not well", "negation;basics"]],
  ["FC037", ["bad / not well", "Negative rating or state.", "I haven\u2019t been doing very well lately.", "state;negation"]],
  ["FC038", ["ordinary / so-so / average", "Describes something average or unremarkable; it can also mean \u201Cgenerally\u201D.", "This restaurant is just average.", "description;rating"]],
  ["FC039", ["How have you been lately?", "Respectful version of asking how someone has been lately.", "How have you been lately?", "greeting;formal"]],
  ["FC040", ["I am very well.", "Positive reply about your own state.", "How have you been lately? I\u2019m doing very well.", "response;greeting"]],
  ["FC041", ["Are you all well?", "Closed question addressed to several people.", "We are doing all right.", "question;plural"]],
  ["FC042", ["We are doing all right.", "Colloquial and moderately positive reply about a group\u2019s state.", "How have you all been lately? We\u2019re doing all right.", "response;plural"]],
  ["FC043", ["what about\u2026? / and-you particle", "After a topic, it returns the same question: \u201Cand you?\u201D, \u201Cand him?\u201D.", "And you?", "particle;question"]],
  ["FC044", ["What about you?", "Asks the same point about the other person without repeating the whole sentence.", "I\u2019m very well, and you?", "question;conversation"]],
  ["FC045", ["big / large", "Basic adjective; part of \u5927\u5BB6.", "everyone / everybody", "adjective;character"]],
  ["FC046", ["home / family / household", "Depending on context it can mean the place where one lives, the home, or the family; it is also part of \u5927\u5BB6.", "my home / my family", "noun;family;basics"]],
  ["FC047", ["everyone / everybody", "Collective pronoun for a group of people; it does not equal \u201Cevery\u201D before just any noun.", "Hello everyone!", "plural;greeting"]],
  ["FC048", ["also / too", "Adverb that usually goes before the verb or predicate.", "I am also very well.", "adverb;basics"]],
  ["FC049", ["Which marks are used to punctuate Chinese?", "\uFF0C, \u3002, \uFF01 and \uFF1F are used, without opening marks.", "Hello! How are you?", "punctuation;writing"]],
  ["FC050", ["Why is it worth knowing Chinese customs when choosing a gift?", "Some gifts are avoided for their sound or cultural associations; these are not universal rules.", "giving a gift", "culture;gifts"]],
  ["FC051", ["Why do some people avoid giving clocks?", "Because \u9001\u949F (\u201Cgiving a clock\u201D) sounds like an expression related to death.", "Don\u2019t give a clock.", "culture;gifts;homophone"]],
  ["FC052", ["Why do some people avoid giving umbrellas?", "Because \u4F1E (\u201Cumbrella\u201D) sounds similar to \u6563 (\u201Cto part\u201D).", "giving an umbrella", "culture;gifts;homophone"]],
  ["FC053", ["Why do some people avoid giving pears?", "Because \u68A8, \u201Cpear\u201D, sounds like \u79BB, \u201Cto part\u201D or \u201Cto go away\u201D.", "giving a pear", "culture;gifts;homophone"]],
  ["FC054", ["Why do some people avoid giving shoes?", "Because \u978B (\u201Cshoes\u201D) sounds similar to \u90AA (\u201Cevil\u201D).", "giving shoes", "culture;gifts;homophone"]],
  ["FC055", ["Why is giving a green hat considered inappropriate?", "Because \u6234\u7EFF\u5E3D\u5B50, \u201Cto wear a green hat\u201D, means that a man\u2019s partner has been unfaithful to him.", "to be on the receiving end of unfaithfulness", "culture;gifts;expression"]],
  ["FC056", ["dad / father (usual form)", "The familiar, everyday way to refer to one\u2019s father.", "my father", "family"]],
  ["FC057", ["mom / mother (usual form)", "The familiar, everyday way to refer to one\u2019s mother.", "my mother", "family"]],
  ["FC058", ["paternal grandfather", "One\u2019s father\u2019s father.", "my paternal grandfather", "family"]],
  ["FC059", ["paternal grandmother", "One\u2019s father\u2019s mother.", "my paternal grandmother", "family"]],
  ["FC060", ["maternal grandfather", "One\u2019s mother\u2019s father. \u5916 marks the maternal side; the term varies by region.", "maternal grandfather", "family"]],
  ["FC061", ["maternal grandmother", "One\u2019s mother\u2019s mother. \u5916 marks the maternal side; the term varies by region.", "maternal grandmother", "family"]],
  ["FC062", ["of / possessive or attributive particle", "Connects the possessor and the possessed: A \u7684 B means \u201Cthe B of A\u201D.", "my mother", "particle;possession"]],
  ["FC063", ["When is \u7684 usually dropped before a kinship term?", "With close relatives it is often dropped: \u6211\u5988\u5988 is more natural than \u6211\u7684\u5988\u5988.", "my mother", "possession;family"]],
  ["FC064", ["my mother (explicit possessive form, with emphasis or contrast)", "The form with \u7684, used especially for contrast or emphasis; in a neutral mention \u6211\u5988\u5988 is more common.", "This is my mother.", "family;possession"]],
  ["FC065", ["my mother (usual familiar form, without the particle)", "The ordinary form that drops \u7684 because the relation is close.", "My mother\u2019s surname is Xu.", "family;possession"]],
  ["FC066", ["China", "The name of the country.", "China", "country"]],
  ["FC067", ["Japan", "The name of the country.", "Japan", "country"]],
  ["FC068", ["South Korea", "Common Mandarin name for South Korea.", "South Korea", "country"]],
  ["FC069", ["to be called / to name", "Used to say someone\u2019s full name or the name by which they are known.", "My name is Xiaoming.", "verb;introduction"]],
  ["FC070", ["to be surnamed / surname", "As a verb, it indicates a person\u2019s family name.", "His surname is Wu.", "verb;surname"]],
  ["FC071", ["name", "Refers to a person\u2019s name; depending on context it can cover the full name.", "What is your name?", "noun;introduction"]],
  ["FC072", ["to be", "Copular verb used to identify or classify; usually not used to link a subject to a simple adjective.", "I am Jos\u00E9.", "verb;basics"]],
  ["FC073", ["In what order do surname and given name go in Chinese?", "The surname (\u59D3) usually comes before the given name (\u540D).", "Zhang is the surname and Xin the given name.", "name;surname"]],
  ["FC074", ["How many characters does a Chinese surname usually have?", "Most have a single character, though compound surnames also exist.", "Surnames of one character.", "surname;character"]],
  ["FC075", ["How many characters does a Chinese given name usually have?", "It usually has one or two characters chosen for their sound and meaning.", "Examples of one-and-two-character given names.", "name;character"]],
  ["FC076", ["My name is Jan.", "Pattern \u6211\u7684\u540D\u5B57\u53EB + name; in everyday conversation \u6211\u53EB + name is usually enough.", "My name is Jan.", "introduction;pattern"]],
  ["FC077", ["My name is Xiaoming.", "Pattern \u6211\u53EB + name.", "My name is Xiaoming.", "introduction;pattern"]],
  ["FC078", ["His surname is Wu.", "Pattern subject + \u59D3 + surname.", "His surname is Wu.", "surname;pattern"]],
  ["FC079", ["Hello everyone! My name is Dani.", "Short, natural introduction in front of a group.", "Hello everyone! My name is Dani.", "homework;introduction"]],
  ["FC080", ["My surname is Garc\u00EDa and my given name is Carla.", "Combines \u59D3 for the surname and \u53EB for the given name.", "My surname is Garc\u00EDa and my given name is Carla.", "homework;surname;name"]],
  ["FC081", ["Hello everyone! How have you all been lately?", "Natural greeting and question to several people.", "Hello everyone! How have you all been lately?", "homework;greeting"]],
  ["FC082", ["Hello, I\u2019m Jos\u00E9 and this is F\u00E1tima.", "Introduces the speaker and another person.", "Hello, I\u2019m Jos\u00E9 and she is F\u00E1tima.", "homework;introduction"]],
  ["FC083", ["Hello, my name is Manuel and my father is called Pablo.", "Natural example of a personal and family introduction.", "Hello, my name is Manuel and my father is called Pablo.", "homework;family"]],
  ["FC084", ["My mother\u2019s surname is Xu and mine is Liu.", "Example contrasting two family surnames.", "My mother\u2019s surname is Xu and my surname is Liu.", "homework;family;surname"]],
  ["FC085", ["dry land (in compounds) / surname Lu", "It means \u201Cdry land\u201D in some compounds and is also the surname L\u00F9.", "surname Lu", "character;surname"]],
  ["FC086", ["Hello, my name is Zhang Xin.", "Example of a Chinese name with the surname before the given name.", "Hello, my name is Zhang Xin.", "introduction;name"]],
  ["FC087", ["My father\u2019s surname is Liu.", "Natural family pattern without \u7684 + \u59D3 + surname.", "My father\u2019s surname is Liu.", "family;surname"]],
  ["FC088", ["what", "Interrogative for \u201Cwhat\u201D or \u201Cwhich\u201D; it sits in the place of the unknown information.", "What is your name?", "interrogative;open_question"]],
  ["FC089", ["who", "Interrogative for people; both pronunciations are common.", "Who is called Wang Ze?", "interrogative;open_question"]],
  ["FC090", ["Where is an interrogative placed in a Chinese open question?", "It occupies the same position the unknown information would have, without changing the basic word order.", "My father is called Zhang Hua. \u2192 Who is called Zhang Hua?", "grammar;open_question"]],
  ["FC091", ["My father is called Zhang Hua.", "Affirmative sentence that serves as the base for two open questions.", "What is my father\u2019s name?", "family;name"]],
  ["FC092", ["Who is called Zhang Hua?", "\u8C01 replaces the unknown person who takes the subject position.", "My father is called Zhang Hua.", "interrogative;who"]],
  ["FC093", ["What is my father\u2019s name?", "\u4EC0\u4E48\u540D\u5B57 substitutes the unknown name after \u53EB.", "My father is called Zhang Hua.", "interrogative;what"]],
  ["FC094", ["This is his name.", "Affirmative sentence with possession and \u540D\u5B57.", "Whose name is this?", "possession;name"]],
  ["FC095", ["Whose name is this?", "\u8C01\u7684 means \u201Cwhose\u201D or \u201Cof whom\u201D.", "This is his name.", "interrogative;possession"]],
  ["FC096", ["My paternal grandmother\u2019s surname is Shen.", "Affirmative sentence used as the base of a question with \u4EC0\u4E48.", "What is my paternal grandmother\u2019s surname?", "family;surname"]],
  ["FC097", ["What is my paternal grandmother\u2019s surname?", "\u4EC0\u4E48 replaces the unknown surname.", "My paternal grandmother\u2019s surname is Shen.", "interrogative;surname"]],
  ["FC098", ["Your paternal grandfather is called Wang Ze.", "Affirmative sentence used as the base of a question with \u8C01.", "Who is called Wang Ze?", "family;name"]],
  ["FC099", ["Who is called Wang Ze?", "\u8C01 replaces the unknown subject.", "Your paternal grandfather is called Wang Ze.", "interrogative;who"]],
  ["FC100", ["What is your name? (polite)", "Polite question about the name using the treatment \u60A8.", "My name is Dani.", "formal;name"]],
  ["FC101", ["Who is called Wang Qiang?", "Open question asking about the person with that name.", "My name is Wang Qiang.", "interrogative;name"]],
  ["FC102", ["My paternal grandfather is called Wang Qiang.", "Affirmative sentence about the paternal grandfather\u2019s name.", "What is your paternal grandfather\u2019s name?", "family;name"]],
  ["FC103", ["above / up / previous", "Component of \u4E0A\u5348 and \u65E9\u4E0A.", "in the morning", "direction;character"]],
  ["FC104", ["below / down / next", "Component of \u4E0B\u5348.", "in the afternoon", "direction;character"]],
  ["FC105", ["noon (character used in compounds)", "Not usually used alone with the everyday sense of \u201Cnoon\u201D; it appears in words like \u4E0A\u5348, \u4E2D\u5348, and \u4E0B\u5348.", "at noon", "time;character"]],
  ["FC106", ["morning (from early on)", "The morning from early until before noon; it does not mark exact hours.", "Good morning!", "time;greeting"]],
  ["FC107", ["morning (period before noon)", "The period before noon, useful when placing activities or schedules.", "I have class in the morning.", "time"]],
  ["FC108", ["noon / midday", "The period around noon; it has no exact hour limits.", "See you at noon.", "time"]],
  ["FC109", ["afternoon", "The period after noon and before evening; it has no exact hour limits.", "Good afternoon!", "time;greeting"]],
  ["FC110", ["evening / night", "The period from dusk until before going to sleep; it has no exact hour limits.", "Good evening!", "time;greeting"]],
  ["FC111", ["early hours / before dawn", "The period between midnight and dawn; it has no exact hour limits.", "early hours", "time"]],
  ["FC112", ["Which greetings with \u597D are formed with a time of day?", "The most common are \u65E9\u4E0A\u597D, \u4E0B\u5348\u597D, and \u665A\u4E0A\u597D. Plain \u4F60\u597D may also be used.", "Good afternoon!", "pattern;greeting"]],
  ["FC113", ["Good morning! (explicit morning greeting)", "Explicit morning greeting.", "Good morning, I\u2019m Wang Fang.", "greeting;morning"]],
  ["FC114", ["Good afternoon! (general afternoon greeting)", "Explicit afternoon greeting.", "Good afternoon!", "greeting;afternoon"]],
  ["FC115", ["Good morning! (short form)", "Short greeting common in Taiwan or in writing. In mainland China, \u65E9\u4E0A\u597D is usually preferred.", "Good morning!", "greeting;morning"]],
  ["FC116", ["Good afternoon / good day (regional or formal)", "Regional or formal greeting for midday or afternoon; uncommon in mainland China.", "Good afternoon!", "greeting;afternoon"]],
  ["FC117", ["Good night! (farewell)", "Used mainly when saying goodbye at night or before going to sleep, not as a general opening greeting.", "Good night!", "greeting;farewell"]],
  ["FC118", ["Goodbye! / See you later!", "Standard farewell.", "See you later!", "farewell"]],
  ["FC119", ["Bye! / Bye-bye!", "Informal farewell taken from English \u201Cbye-bye\u201D.", "Bye!", "farewell;informal"]],
  ["FC120", ["Good evening. What is your surname? (polite)", "Night greeting followed by the polite formula \u60A8\u8D35\u59D3 to ask the surname.", "My surname is Sun.", "dictation;formal;surname"]],
  ["FC121", ["My surname is Sun.", "Reply with the pattern \u6211\u59D3 + surname.", "What is your surname?", "dictation;surname"]],
  ["FC122", ["Good morning. Who is Wang Fang?", "Morning greeting followed by an identification question.", "Good morning, I\u2019m Wang Fang.", "dictation;identification"]],
  ["FC123", ["Good morning, I\u2019m Wang Fang.", "Identification reply with \u6211\u662F + name.", "Who is Wang Fang?", "dictation;introduction"]],
  ["FC124", ["milk / dairy (as a component)", "It means \u201Cmilk\u201D and appears in \u5976\u8336. For cow\u2019s milk, \u725B\u5976 is used.", "milk tea", "drink;ingredient"]],
  ["FC125", ["tea", "Noun and component of \u5976\u8336 and \u73CD\u73E0\u5976\u8336.", "milk tea", "drink;ingredient"]],
  ["FC126", ["pearl", "In \u73CD\u73E0\u5976\u8336 it refers to the tapioca balls, similar to pearls.", "bubble tea with tapioca pearls", "drink;ingredient"]],
  ["FC127", ["bubble tea / milk tea with tapioca", "Literally \u201Cmilk tea with pearls\u201D.", "I like bubble tea.", "drink"]],
  ["FC128", ["What is pinyin?", "A system that represents Mandarin pronunciation with Latin letters and tones.", "n\u01D0 h\u01CEo", "pronunciation;writing"]],
  ["FC129", ["Why are tones important in Mandarin?", "Tones distinguish words. There are four main tones and one neutral tone.", "The four main tones and the neutral tone, illustrated with ma.", "pronunciation;tone"]],
  ["FC130", ["On what kind of letter is a tone mark placed in pinyin?", "It is placed over a vowel; consonants never carry a tone mark.", "The mark is on the vowel i.", "pinyin;tone;rule"]],
  ["FC131", ["Which vowel takes the tone mark when there are several?", "a, o, and e have priority. In iu and ui, the mark goes on the second vowel.", "In ao, the mark goes on the a.", "pinyin;tone;rule"]],
  ["FC132", ["Which vowel takes the tone mark in iu and ui?", "On the second vowel: for example, li\u00FA and gu\u01D0.", "to stay / ghost", "pinyin;tone;rule"]],
  ["FC133", ["How many tone marks can there be per syllable?", "Only one, even when the syllable has several vowels.", "how about / how", "pinyin;tone;rule"]],
  ["FC134", ["How is \u00FC written after j, q, x, or with no initial?", "After j, q, or x it loses its two dots: ju, qu, xu. With no initial it is written with y: yu.", "woman; go; rain", "pinyin;umlaut;rule"]],
  ["FC135", ["Go for it! / Come on!", "Used to cheer someone on or encourage them.", "Come on, everyone!", "encouragement;expression;basics"]],
  ["FC136", ["when", "Interrogative to ask when something happens; it occupies the position of the time expression.", "When do you shower?", "interrogative;time;open_question"]],
  ["FC137", ["to run / to go running", "The common verb for running as an activity or exercise; \u8DD1 means \u201Cto run\u201D more generally.", "I go running every morning.", "verb;activity;routine"]],
  ["FC138", ["to shower / to bathe", "Everyday expression for washing one\u2019s body; depending on context it can mean \u201Cto shower\u201D or \u201Cto bathe\u201D.", "I shower at night.", "verb;hygiene;routine"]],
  ["FC139", ["drink milk", "\u559D means \u201Cto drink\u201D and \u725B\u5976 is the usual way to say \u201Cmilk\u201D.", "I drink milk every morning.", "drink;verb;routine"]],
  ["FC140", ["zero", "The number zero.", "zero, one, two", "number;basics"]],
  ["FC141", ["one", "The number one. Its tone often changes in speech depending on the following syllable, but the dictionary form is y\u012B.", "zero, one, two", "number;basics"]],
  ["FC142", ["two", "It means \u201Ctwo\u201D. For counting objects, \u4E24 (li\u01CEng) is usually used.", "one, two, three", "number;basics"]],
  ["FC143", ["three", "The number three.", "two, three, four", "number;basics"]],
  ["FC144", ["four", "The number four.", "three, four, five", "number;basics"]],
  ["FC145", ["five", "The number five.", "four, five, six", "number;basics"]],
  ["FC146", ["six", "The number six.", "five, six, seven", "number;basics"]],
  ["FC147", ["seven", "The number seven.", "six, seven, eight", "number;basics"]],
  ["FC148", ["eight", "The number eight.", "seven, eight, nine", "number;basics"]],
  ["FC149", ["nine", "The number nine.", "eight, nine, ten", "number;basics"]],
  ["FC150", ["ten", "The number ten. From 11 to 19, \u5341 goes before the unit.", "nine, ten, eleven", "number;basics"]],
  ["FC151", ["eleven", "Formed with \u5341 + \u4E00: ten plus one.", "ten, eleven, twelve", "number;compound"]],
  ["FC152", ["fifteen", "Formed with \u5341 + \u4E94: ten plus five.", "fourteen, fifteen, sixteen", "number;compound"]],
  ["FC153", ["twenty", "Formed with \u4E8C + \u5341: two tens.", "nineteen, twenty, twenty-one", "number;tens"]],
  ["FC154", ["twenty-one", "Formed with \u4E8C + \u5341 + \u4E00: two tens plus one.", "twenty, twenty-one, twenty-two", "number;compound"]],
  ["FC155", ["thirty-five", "Formed with \u4E09 + \u5341 + \u4E94: three tens plus five.", "thirty-five", "number;compound"]],
  ["FC156", ["forty-eight", "Formed with \u56DB + \u5341 + \u516B: four tens plus eight.", "forty-eight", "number;compound"]],
  ["FC157", ["sixty-seven", "Formed with \u516D + \u5341 + \u4E03: six tens plus seven.", "sixty-seven", "number;compound"]],
  ["FC158", ["ninety-nine", "Formed with \u4E5D + \u5341 + \u4E5D: nine tens plus nine.", "ninety-nine", "number;compound"]],
  ["FC159", ["and (joins nouns or noun phrases)", "Joins nouns or noun phrases; it does not link complete actions.", "I like bubble tea and milk.", "conjunction;grammar"]],
  ["FC160", ["and then / afterwards (links actions)", "Connector that introduces an action that comes after another. It orders actions, not nouns.", "I go running, then I shower.", "connector;sequence;grammar"]],
  ["FC161", ["caf\u00E9 / coffee shop", "A place where coffee and other drinks are served; \u5496\u5561\u9986 (k\u0101f\u0113igu\u01CEn) is also common.", "We drink tea at the caf\u00E9.", "place;drink"]],
  ["FC162", ["beach", "An area of sand or pebbles beside the sea.", "We go to the beach.", "place;leisure"]],
  ["FC163", ["restaurant / dining room (general term)", "General term for \u201Crestaurant\u201D; depending on context it can also mean \u201Cdining room\u201D.", "This restaurant is just average.", "place;food"]],
  ["FC164", ["restaurant / hotel (depending on context)", "It can mean \u201Crestaurant\u201D and, depending on the region or the establishment\u2019s name, also \u201Chotel\u201D.", "We go to the restaurant to eat.", "place;food"]],
  ["FC165", ["restaurant / eatery (colloquial)", "Everyday word for a restaurant or small eatery, usually more informal than \u9910\u5385.", "This restaurant is very good.", "place;food;colloquial"]],
  ["FC166", ["to come", "Verb of movement toward where the speaker is or toward the reference point of the conversation.", "When are you coming?", "verb;movement"]],
  ["FC167", ["to do / to make", "General verb for doing, preparing, or carrying out something; the specific meaning depends on the object.", "What are you doing?", "verb;action"]],
  ["FC168", ["to sleep / to go to sleep", "Everyday expression for the action of sleeping or going to bed to sleep.", "I go to bed at eleven at night.", "verb;routine"]],
  ["FC169", ["to work / work", "Can function as a verb, \u201Cto work\u201D, or as a noun, \u201Cwork\u201D.", "My father works at a restaurant.", "verb;noun;routine"]],
  ["FC170", ["Spain", "The name of Spain in Mandarin.", "I come from Spain.", "country;proper_noun"]],
  ["FC171", ["France", "The name of France in Mandarin.", "She comes from France.", "country;proper_noun"]],
  ["FC172", ["to go", "Verb of movement indicating going to a place different from the reference point.", "We go to China in the afternoon.", "verb;movement"]],
  ["FC173", ["to return / to go back", "Indicates returning to a place; before the destination, \u53BB is not used.", "I go home in the evening.", "verb;movement"]],
  ["FC174", ["bubble tea shop", "An establishment specializing in bubble tea and similar drinks.", "We go to the bubble tea shop.", "place;drink"]],
  ["FC175", ["store / shop", "General term for an establishment where products are sold.", "This store is very good.", "place;shopping"]],
  ["FC176", ["Barcelona", "The Mandarin name of the city of Barcelona.", "I live in Barcelona.", "city;proper_noun"]],
  ["FC177", ["where", "Two equivalent forms; \u54EA\u513F is more common in northern China.", "Where are you going?", "interrogative;place"]],
  ["FC178", ["I go home in the evening.", "\u56DE\u5BB6 means \u201Cto go back home\u201D; in this neutral context \u56DE\u6211\u7684\u5BB6 is not said.", "I go home in the evening.", "movement;home;time"]],
  ["FC179", ["Hello, when do they come to the caf\u00E9?", "\u6765 presents the movement toward the caf\u00E9 as the reference point.", "When do they come to the caf\u00E9?", "question;movement;place"]],
  ["FC180", ["She goes to the restaurant at noon and returns home in the afternoon.", "Contrasts \u53BB toward a destination with \u56DE for returning home.", "She goes to the restaurant at noon and returns home in the afternoon.", "movement;routine;time"]],
  ["FC181", ["We are going to China in the afternoon.", "The time usually goes between the subject and the verb.", "We are going to China in the afternoon.", "movement;time;country"]],
  ["FC182", ["He comes to the restaurant at noon.", "\u6765 presents the restaurant as the point toward which the person moves.", "He comes to the restaurant at noon.", "movement;time;place"]],
  ["FC183", ["He and his father go to the caf\u00E9 at noon.", "\u548C joins the two subjects; \u4E2D\u5348 appears before the verb \u53BB.", "He and his father go to the caf\u00E9 at noon.", "movement;family;place"]],
  ["FC184", ["to eat", "General verb for ingesting food; it can take the food as its object.", "What do you eat?", "verb;food"]],
  ["FC185", ["to eat / to have a meal", "General expression for having a meal; \u996D here does not point to a specific dish.", "When do you eat?", "verb;food;routine"]],
  ["FC186", ["water", "Basic drink and the general term for water.", "I drink water.", "drink;basics"]],
  ["FC187", ["orange juice", "Drink made with oranges; \u6A59 means \u201Corange\u201D and \u6C41, \u201Cjuice\u201D.", "I drink orange juice.", "drink;fruit"]],
  ["FC188", ["beer", "Alcoholic drink whose name contains \u9152, \u201Calcoholic drink\u201D.", "a bottle of beer", "drink;alcohol"]],
  ["FC189", ["bottle / measure word for bottles", "As a measure word it goes between the number and a bottled drink.", "a bottle of beer", "classifier;container"]],
  ["FC190", ["to want / to wish", "Expresses the desire to obtain or do something.", "I want a bottle of beer.", "verb;desire"]],
  ["FC191", ["I want a bottle of beer.", "Pattern \u60F3\u8981 + number + measure word + noun.", "I want a bottle of beer.", "drink;classifier;desire"]],
  ["FC192", ["What do you eat? / What are you going to eat?", "\u4EC0\u4E48 occupies the place of the food being asked about.", "What do you eat?", "question;food"]],
  ["FC193", ["When do you eat?", "\u4EC0\u4E48\u65F6\u5019 goes before the verb to ask about the moment.", "When do you eat?", "question;food;time"]],
  ["FC194", ["cooked rice", "Rice that has already been cooked; for the uncooked grain, \u5927\u7C73 is used.", "I eat rice.", "food;rice"]],
  ["FC195", ["noodles", "General term for noodles.", "I eat noodles.", "food;noodles"]],
  ["FC196", ["bread", "Baked product made from flour.", "I eat bread.", "food;bread"]],
  ["FC197", ["pizza", "The common Mandarin transcription of \u201Cpizza\u201D.", "I want to eat pizza.", "food;loanword"]],
  ["FC198", ["hamburger", "\u6C49\u5821 and \u6C49\u5821\u5305 are common forms for a hamburger.", "I want to eat a hamburger.", "food;loanword"]],
  ["FC199", ["Chinese food / Chinese cuisine", "\u83DC can mean \u201Cdish\u201D or \u201Ccuisine\u201D; here it refers to China\u2019s cuisine.", "I like Chinese food.", "food;country"]],
  ["FC200", ["steamed stuffed bun (baozi)", "A filled dough that is usually steamed.", "I eat a steamed bun.", "food;dough"]],
  ["FC201", ["dumpling (jiaozi)", "A filled piece of dough that can be boiled, steamed, or fried.", "I like eating dumplings.", "food;dough"]],
  ["FC202", ["french fries", "Fried potato strips; \u85AF refers to tubers and \u6761 describes the elongated shape.", "I want to eat french fries.", "food;potato"]],
  ["FC203", ["hand-pulled noodles", "In Mandarin it refers to noodles made by stretching the dough; Japanese ramen is \u65E5\u5F0F\u62C9\u9762.", "I want to eat hand-pulled noodles.", "food;noodles"]],
  ["FC204", ["handsome guy", "Colloquial way to refer to a young, attractive man; it can also be used to get someone\u2019s attention.", "He is a handsome guy.", "person;colloquial"]],
  ["FC205", ["beautiful woman / pretty girl", "Colloquial way to refer to an attractive woman; it can also be used to get someone\u2019s attention.", "She is a beautiful woman.", "person;colloquial"]],
  ["FC206", ["friend", "A person with whom one has a friendship.", "This afternoon I\u2019m going with a friend to eat Chinese food.", "person;friendship"]],
  ["FC207", ["boyfriend", "Male partner in a romantic relationship.", "She comes to Spain at noon with her boyfriend.", "person;partner"]],
  ["FC208", ["girlfriend", "Female partner in a romantic relationship.", "She is my girlfriend.", "person;partner"]],
  ["FC209", ["to like / to love", "Expresses affection for a person or liking for something; depending on context it matches \u201Cto like\u201D or \u201Cto love\u201D.", "I like Chinese food.", "verb;preference;affection"]],
  ["FC210", ["Really?", "\u771F\u7684 asks whether something is true and \u5417 turns it into a yes/no question.", "Really?", "question;confirmation;conversation"]],
]);